### PR TITLE
Added condtional wrap for Twitter usernames

### PR DESCRIPTION
**Pull request by kemiljk**
Users who wish to share their usernames can now have them added in the supporters.ts file. This will then be picked up by the conditionalwrap inside the index.tsx file. Added some simple styling to indicate that the account with a Twitter profile is different via font-weight 900.

### CODE REVIEW

**Comment by kemiljk** [comment]
Tweaked to include a tiny bit of commenting and removed a trailing semicolon which is why the build now passes.

**Comment by brianlovin** [comment]
Hey quick one before I review: can you remove the `yarn.lock` file and use `npm install` instead? That way it will only ever use the `package-lock.json` file :)

**Comment by kemiljk** [comment]
Oh yeah, whoops, installed a dependency via yarn instead of npm. I’ll correct and update shortly.

**Comment by kemiljk** [comment]
Should be fixed now but let me know.

**Comment by brianlovin** [comment]
Made some small changes @kemiljk but this looks good! Thanks a bunch :)

**Comment by kemiljk** [comment]
Awesome. I’m sure you’d have written faster alone but glad to have contributed something. The tweaks look much more logical and visually nicer. Swish!

**Comment by brianlovin** [comment]
No worries at all, appreciate you taking the time to dig in on the code :)

**Pull request merged**
